//export var LANGUAGE: string;

export default {
  sv: {
    welcome: "Välkommen",
    settings_title_1: "Inställningar",
    settings_title_2: "Språk",
    settings_opt_label_1: "Musik",
    settings_opt_label_2: "Ljud",
    settings_opt_label_3: "Helskärm",
    helpmenu_title: "VINSTTABELL",
    gameinfomenu_title: "Spelregler",
    msg_error_credits: "Otillräckliga medel",
    msg_play: "Spelet fortsätter",
    msg_win: "Du vann",
    msg_win_jp: "Du vann Jackpot!",
    msg_totalwin: "Total vinst",
    msg_bonus: "Fortsätt till bonusspelet",
    msg_freebet: "Gratisspel",
    msg_nowins: "Ingen vinst denna gång!",
    freespin_text: `     \n Du har vunnit       Freespins`,
    freespin_rewards_text_1: `Grattis!`,
    freespin_rewards_text_1A: `\n Du har vunnit `,
    freespins: "freespinssv",
    max_bet: `  MAX INSATS`,
    coin: "Mynt",
    coins: "Mynt",
    coins_won: "Mynt vinst:",
    continue: "FORTSÄTT",
    bet: "Insats",
    bet_value: "Insats",
    balance: "Saldo",
    lines: "Linjer",
    line: "Linje",
    game_rules: "Spelregler",
    paytable: "Vinsttabell",
    autoplay: "AUTOSPINN",
    settings: "Inst'llningar",
    desc_jp_sym: "Jackpot",
    freebet_payout: `3 eller fler på skärmen \n för att erhålla freespins`,
    scatter_payout: `3 på skärmen för \n att få en bonus`,
    wild_symbol1: `Wild ersätter alla symboler \n förutom scatter samt bonus \n Betalar som den symbol \n som betalar högst`,
    wild_symbol2: "utom Fyr och Manet.",
    wild_symbol3: "Betalar som den symbol som betalar mest",
    session_expire: `<h3>Sessionen går ut</h3><div><p>Du har varit inaktiv för länge. Uppdatera sidan om du vill fortsätta spela med oss.</p></div>`,
    reality_check_1: "<div> <h3> ",
    reality_check_1A: " </h3> <div> <p>",
    reality_check_1B: "<div> <h3> " + "Sessionspåminnelse </h3> <div> <p>" + "  Du har vunnit ",
    reality_check_2: "  ",
    reality_check_2B: " och förlorat ",
    //  reality_check_3: `</p><p>Önskar du att fortsätta spela?</p><p><a href='#' onclick=\"quitOverlay('Tack för att du spelar!')\">Avsluta</a></p>`,
    reality_check_3: `</p><button onclick="quitOverlay('Tack för att du spelar!')"; class="button button1";>Avsluta</button></p>`,
    reality_check_3A: `</p><p>Önskar du att fortsätta spela?</p><p><a href='#' onclick=\"quitOverlay('Tack för att du spelar!')\">Avsluta</a></p> `,
    //reality_check_3B: `' onclick='overlay()'>Avsluta</a></p> `,
    reality_check_3B: `'target="_top"; onclick='overlay()'><button class="button button1";>Avsluta</button></a></p>`,
    //reality_check_4: `<p><a href='#' onclick='closeOverlay()'>Fortsätt</a></p>`,
    reality_check_4: `</p><button onclick="closeOverlay()"; class="button button2"; id="button2">Fortsätt</button></p>`,
    reality_check_5A: `<p><a href='`,

    //reality_check_5: `<p><a href='` + game_data.lobby_url + `' onclick='overlay()'>Home</a></p> `,
    //reality_check_5: `' onclick='overlay()'>Hem</a></p> `,
    //newcorrect//
    reality_check_5: `'target="_top"; onclick='overlay()'><button class="button button3";>Hem</button></a></p>`,
    //reality_check_6: `' onclick='overlay()'>Hitorik</a></p> </div></div> `,
    reality_check_6: `'target="_top"; onclick='overlay()'><button class="button button4";>Hitorik</button></a></p>`,
    //  reality_check_7: `<p><a href='#' onclick="location.reload();">Ladda om</a></p> </div></div> `
    reality_check_7: `<p><a href='#' onclick="location.reload();"><button  class="button button5";>Ladda om</button></a></p>`,
    win: "Vinst",
    bonus_stats_1: "   Styrka: ",
    bonus_stats_2: "   Snabbhet: ",
    bonus_stats_3: "   Vinnarskalle: ",
    bonus_stats_4: "   Kusk: ",
    bonus_stats_5: "   Tränare: ",
    bonus_5: "Nivå   ",
    bonus_6: "Vinnare :  ",
    bonus_7: "Välj din!",
    bonus_8: "Resultat",
    bonus_9: "Bonus ger ytterligare ",
    bonus_10: " Multiplikator",
    bonus_11: `Grattis! \n du går vidare till nästa lopp`,
    bonus_12: `Awwww!  \n bättre lycka nästa gång!`,
    bonus_13: `häst`,
    utils_0: `Your browser or device is not supported`,
    sign_0: `  Den 14:e augusti 2015 satte Delicious världsrekord på \n Bollnästravet med tiden 1.08,6 på distansen 1640 m. `,
    sign_1: `  Den 29:e augusti 2015 satte Delicious världsrekord på \n Bergsåker med tiden 1.10,0 på distansen 2140 m. `,
    sign_2: `  Den 24:e oktober 2015 satte Delicious världsrekord på \n Jägersro på med tiden 1.12,1 på distansen 2640 m.  `,
    sign_3: `     Delicious vann 29 av sina 55 starter under åren \n 2012-2017 `,
    sign_4: `       2015 vann Delicious utmärkelsen Årets Häst.`,
    sign_5: `Den 7:e mars 2020 föder Delicious sitt första föl, en \n hingst med namnet Heavenly Zet med pappan Daley Lovin`

  },
  en: {
    welcome: "Welcome",
    settings_title_1: "Settings",
    settings_title_2: "Language",
    settings_opt_label_1: "Sound",
    settings_opt_label_2: "Music",
    settings_opt_label_3: "Fullscreen",
    helpmenu_title: "Paytable",
    gameinfomenu_title: "Game rules",
    freespins: "freespinsen",
    msg_error_credits: "No credits!",
    msg_play: "Game is running ...",
    msg_win: "You Win",
    msg_win_jp: "You Win the Jackpot!",
    msg_totalwin: "Total Win",
    msg_nowins: "No win this time!",
    coin: "Coin",
    bet: "Bet",
    bet_value: "Bet",
    balance: "Balance",
    win: "Win",
    lines: "Lines",
    paytable: "Paytable",
    autoplay: "Autoplay",
    settings: "Settings",
    desc_jp_sym: "Jackpot"
  },
  de: {
    welcome: "Willkommen",
    settings_title_1: "Einstellungen",
    settings_title_2: "Sprache",
    settings_opt_label_1: "Soundeffekte",
    settings_opt_label_2: "Musik",
    settings_opt_label_3: "Vollbild",
    helpmenu_title: "Gewinntabelle",
    gameinfomenu_title: "Game rules",
    msg_error_credits: "Keine Kredits!",
    msg_play: "Spiel läuuft ...",
    msg_win: "Gewonnen",
    msg_win_jp: "Du hast den Jackpot gewonnen!",
    msg_totalwin: "Gesamt gewinn",
    msg_nowins: "Verloren!",
    coin: "Munt",
    bet: "Munt",
    bet_value: "Munt",
    balance: "Brieftasche",
    lines: "Linien",
    paytable: "Auszahlungstabelle",
    autoplay: "Autoplay",
    settings: "Einstellungen",
    desc_jp_sym: "Jackpot"
  },
  es: {
    welcome: "Bienvenida",
    settings_title_1: "Ajustes",
    settings_title_2: "Idioma",
    settings_opt_label_1: "Efectos sonoros",
    settings_opt_label_2: "Música",
    settings_opt_label_3: "Pantalla completa",
    helpmenu_title: "Tabla de ganancia",
    gameinfomenu_title: "Game rules",
    msg_error_credits: "Sin crédito!",
    msg_play: "El juego se está ejecutando ...",
    msg_win: "Won",
    msg_win_jp: "Te has ganado la bote!",
    msg_totalwin: "Beneficio total",
    msg_nowins: "Perdido!",
    coin: "Acuñar",
    bet: "Acuñar",
    bet_value: "Acuñar",
    balance: "Saldo",
    lines: "Líneas",
    paytable: "Tabla de pagos",
    autoplay: "Autoplay",
    settings: "Ajustes",
    desc_jp_sym: "Bote"
  }
};
